# Deep Learning course
## Homework 1

### Initial values

In [33]:
# LengthOfZeroVec: Number of elements in the first vector (full of zeros)
# LengthOfLinearVec: Number of elements is the second vector (with elements a_i = i)
# Coordinate: Indicate Pauli matrices. Could be 'X', 'Y' or 'Z'

LengthOfZeroVec = 5
LengthOfLinearVec = 10
Coordinate = 'Y'

In [34]:
import sys as s
import numpy as np

### Generating zero vector

In [35]:
def ZeroVector(Length):
    # Create vector of zeros
    ZeroVec = np.zeros((Length,1), dtype=int)
    return(ZeroVec)

In [36]:
# Print vector full of zeros, and shape of the column vector

print('Column vector full of zeros:', '\n', ZeroVector(LengthOfZeroVec))
print('Shape: ', ZeroVector(LengthOfZeroVec).shape, '\n')

Column vector full of zeros: 
 [[0]
 [0]
 [0]
 [0]
 [0]]
Shape:  (5, 1) 



### Generating vector with elements a_i = i

In [37]:
def LinearVector(Length):
    #Create vector with a_i = i elements
    LinearVec = np.linspace(1,Length,num=Length)
    return(LinearVec)

In [38]:
# Print the "Lin.vec." and the sum of its elements

print('Column vector, with a_i = i elements:', '\n', LinearVector(LengthOfLinearVec))
print('Sum: ', sum(LinearVector(LengthOfLinearVec)), '\n')

Column vector, with a_i = i elements: 
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Sum:  55.0 



### Generating Pauli matrices

In [39]:
def PauliMatrices():
    #Create Pauli-matrices
    PauliX = np.array([[0.,1.],
              [1.,0.]])
    PauliY = np.array([[0.,-1.j],
              [1.j,0.]])
    PauliZ = np.array([[1.,0.],
              [0.,-1.]])
    return(PauliX, PauliY, PauliZ)

In [40]:
# Print the Pauli matrices

print('PauliX:', '\n', PauliMatrices()[0], '\n')
print('PauliY:', '\n', PauliMatrices()[1], '\n')
print('PauliZ:', '\n', PauliMatrices()[2], '\n')

PauliX: 
 [[0. 1.]
 [1. 0.]] 

PauliY: 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]] 

PauliZ: 
 [[ 1.  0.]
 [ 0. -1.]] 



### Checking generated Pauli matrices

In [41]:
def PauliCheck(Coordinate): # coordinate can be 'X', 'Y' or 'Z'    
    CoordIndexMap = {'X':0, 'Y':1, 'Z':2}
    PauliIndex = CoordIndexMap[Coordinate]

    # Retrieve Pauli matrix
    PauliActual = PauliMatrices()[PauliIndex]

    # Calculate the Pauli's determinant
    Determinant = np.linalg.det(PauliActual)

    # Calculate the Pauli's square
    Square = np.square(PauliActual)

    # Calculate the Pauli's trace
    Trace = np.trace(PauliActual)

    return(Determinant, Square, Trace)

In [42]:
# Print them

print('Determinant of Pauli', Coordinate, ': ', PauliCheck(Coordinate)[0])
print('Square of Pauli', Coordinate, ':', '\n', PauliCheck(Coordinate)[1])
print('Trace of Pauli', Coordinate, ': ', PauliCheck(Coordinate)[2], '\n')

Determinant of Pauli Y :  (-1+0j)
Square of Pauli Y : 
 [[ 0.+0.j -1.+0.j]
 [-1.+0.j  0.+0.j]]
Trace of Pauli Y :  0j 

